# Streamlit Community Cloud Secrets Configuration
# Add your API keys here when deploying to Streamlit Community Cloud

# Optional: Tavily API Key for enhanced literature search
# TAVILY_API_KEY = "your_tavily_api_key_here"

# Optional: HuggingFace Token for enhanced models
# HUGGINGFACE_TOKEN = "your_huggingface_token_here"

# Note: The application works without these API keys using mock data
# For production deployment, add your actual API keys to Streamlit Community Cloud secrets
